frontend/pages/_app.tsx
This file contains the rendering of Chakra UI. 
With this file included, all the rendering that was previously missing (#6) will be fixed.
=> Add _app.tsx

backend/question_repo/Dockerfile, backend/question_repo/docker-compose.yml, backend/user_manager/Dockerfile, backend/user_manager/docker-compose.yml, frontend/Dockerfile, frontend/components/InputField.tsx, frontend/components/Question.tsx, frontend/docker-compose.yml, frontend/stores/questionsStore.js
With containerisation, this ease the deployment and testing of code.
However, the issue of Frontend crashing because Backend has not begin is yet to be resolved here.
=> Create skeleton Docker files for Containerisation

backend/question_repo/controllers/questionsController.js, backend/question_repo/model/question.js, backend/question_repo/server.js, frontend/components/InputField.tsx, frontend/components/Question.tsx, frontend/components/Questions.tsx, frontend/pages/index.tsx, frontend/theme.js, package-lock.json, package.json
Implemented a Icon Button such that it toggles between light mode and dark mode. 
The color scheme will also be changed accordingly
=> Color mode toggle

backend/question_repo/controllers/questionsController.js, backend/question_repo/model/question.js, backend/question_repo/server.js, frontend/components/InputField.tsx, frontend/components/Question.tsx, frontend/components/Questions.tsx, frontend/pages/index.tsx, package-lock.json
Implement a feature to allow the question repo to be updated, as part of the requirement under CRUD.
In this feature, when clicking onto the edit button, the text will be updated on the text field which allows user to edit on and make changes. Changes can be made accordingly but the caveat is that currently, question id is unique and not null (basically a Primary Key), hence it does not allow duplicate. 
If necessary, this changes can be made in subsequent iterations.
A bug in the delete feature has also been identified and was also fixed in this PR. (#21)
=> Implement update on CRUD

.gitignore, backend/collaboration_service/server.js, backend/communication_service/server.js, backend/user_service/src/server.js, frontend/components/VideoCall.tsx, frontend/package-lock.json, frontend/package.json, frontend/pages/_app.tsx, frontend/pages/collaboration.tsx, frontend/pages/index.tsx, package-lock.json, package.json
Added collab space with basic code. Will need to incorporate the question fetching to the page eventually. Video call function is incomplete but at least accessing the webcam works. Anyone good at CSS please save me, my page looks terrible right now.
=> Initial front and back end code for basic collab

frontend/components/ToggleMode.tsx, frontend/components/VideoCall.tsx, frontend/package-lock.json, frontend/package.json, frontend/pages/_app.tsx, frontend/pages/index.tsx
The tab was initially on a separate component and requires commenting to view different services.
I've since move all of those into a tab to allow easy navigation of different services. 
However, when tested on my end, there seems to be an CORS issue. 
Will look into this soon
=> Integrate collab service in collab tab

backend/collaboration_service/server.js
Modified the port used for origin from 3001 to 3000 udner collaboration service.
=> Changed port from 3001 to 3000

backend/collaboration_service/package-lock.json, backend/collaboration_service/package.json, backend/communication_service/package-lock.json, backend/communication_service/package.json
Added the package tracker for the services as it was missing from my initial commit
=> Added package tracker collab and communication

backend/question_service/src/questionmanager.js
Specifically, /questions/create
=> Fix QuestionService Read Operation

.github/workflows/deploy.yml, aws_deploy/docker-compose.yml, frontend/docker-compose.yml
Enhance Github Actions CD to deploy Frontend Service to AWS ECR and AWS Beanstalk too
=> Integrate Frontend Service for Deployment

frontend/components/Question.tsx, frontend/components/QuestionsInputField.tsx
Some of the API call have change the calling method. However, at the time of testing, the deployment was not functional. Hence the API call is changed to localhost and is tested in question_service using npm run dev. The localhost is also running on npm run dev.
=> Refactor question service

backend/question_service/src/questionmanager.js, frontend/components/Question.tsx, frontend/components/QuestionsInputField.tsx, frontend/pages/index.tsx, frontend/theme.js
In this implementation, question description will not be shown at the table, under the description column. Instead, a modal button will shown. When the button is clicked, a full question with image will be shown.
I've also implemented on the side such that when a duplicate key is seen in the entry, it will be shown in the form of an alert border with an error placeholder text.
=> Implement Modal and Error Border

frontend/components/CodeEditor.tsx, frontend/pages/collaboration.tsx
Refactored the code out to make the code more readable, will try to implement matching soon.
=> Refactored code editor from collaboration page

.github/workflows/deploy.yml, aws_deploy/docker-compose.yml, backend/question_scraper/README.md, backend/question_scraper/scraper.js, backend/question_scraper/serverless.js, backend/question_scraper/serverless.yml, backend/question_service/README.md, backend/user_service/README.md
Previously, AWS EB died on us due to insufficient storage and memory.
I increased the instance capacity from t3.small+8gb storage to t3.medium+12gb storage (will scale to t3.large if necessary). This gives us a small buffer in storage and memory.
Fixed QuestionScraper and our Github Actions for CD
Added QuestionScraper Readme for usage instructions
=> Fix Deployment Issues + Finalise QuestionScraper (Lambda Fn)

backend/collaboration_service/server.js, backend/matching_service/db.js, backend/matching_service/model.js, backend/matching_service/package-lock.json, backend/matching_service/package.json, backend/matching_service/server.js, frontend/components/CodeEditor.tsx, frontend/components/MatchButton.tsx, frontend/package-lock.json, frontend/pages/collaboration.tsx, frontend/pages/index.tsx
Matching is sort of working now, 1 user will automatically join the room while the other user need to click the match button again to join, I will try to fix that bug, but joining the same room in collaboration is working.
=> Matching service

backend/collaboration_service/server.js, backend/matching_service/model.js, backend/matching_service/modelController.js, backend/matching_service/server.js, frontend/components/CodeEditor.tsx, frontend/pages/index.tsx
Made some small changes here and there regarding spelling errors and redundant imports.
=> Fixed some bugs

frontend/components/Question.tsx, frontend/components/QuestionsInputField.tsx, frontend/pages/index.tsx
This bug fixes #57. 
By changing the way input values is being assigned, the issue of needing 2 selection would be fixed.
On the note, the alignment and colorScheme of the sign out button is also been improved.
=> Fix double select complexity bug

frontend/components/ToggleMode.tsx, frontend/pages/index.tsx, frontend/pages/signin.tsx
In this PR, I've implemented the following:
- Toggle Button for Dark/Light Mode
- Show/Hide Password
- Icons on the left of Input Field
- Change the "Create Account" to a Button (Previously it was purely a Link)
=> Implement Dark Mode

frontend/pages/profile.tsx
In the implementation, the match found was tested arbitrary with a 2 minute timer. 
The Accept and Decline button has not been implemented yet.
=> Add Match Found Alert

backend/history_service/historyController.js, backend/history_service/historyModel.js, backend/history_service/package-lock.json, backend/history_service/package.json, backend/history_service/server.js, backend/matching_service/modelController.js, frontend/components/History.tsx, frontend/pages/collaboration.tsx, frontend/pages/dashboard.tsx, frontend/pages/history.tsx
Added backend DB for history service. I am thinking of using monaco to display the past codes but it is a big buggy now. Will need to add in inside collab page a button to save all info into the history db.
=> History service

backend/matching_service_rabbitmq/Dockerfile, backend/matching_service_rabbitmq/README.md, backend/matching_service_rabbitmq/custom-rabbitmq.conf, backend/matching_service_rabbitmq/docker-compose.yml, backend/matching_service_rabbitmq/rabbitmqMatchingController.js, backend/matching_service_rabbitmq/server.js, backend/matching_service_rabbitmq/setup-rabbitmq-queue.sh, frontend/components/Matching/MatchingPage.tsx
1. Add dockerized RabbitMQ (do help to check, not very sure on this).
2. Matching Service RabbitMQ is working (matching, timeout, waiting animation).
3. Add README with simple instructions to start RabbitMQ matching service.
=> Implement Basic Matching Service RabbitMQ

frontend/components/Question.tsx, frontend/components/Questions.tsx, frontend/components/QuestionsHeader.tsx, frontend/components/QuestionsInputField.tsx, frontend/pages/dashboard.tsx, frontend/pages/profile.tsx
Previously, the scrollbar seems to be out of the frame when exceeding the count. In this iteration, I've implemented a scrollbar such that when it overflows. It's as shown below:
=> Implement scrollbar for question table

frontend/components/Question.tsx, frontend/components/Questions.tsx, frontend/components/QuestionsInputField.tsx, frontend/pages/_app.tsx, frontend/pages/dashboard.tsx, frontend/pages/profile.tsx
After the previous iteration of the table scroll, I noticed that the table is exceeding beyond the grid. This iteration fix that issue.
=> Fix question service table bug

frontend/components/CategoryTag.tsx, frontend/components/Question.tsx, frontend/components/QuestionsHeader.tsx, frontend/pages/dashboard.tsx, frontend/pages/profile.tsx
This is what I've done:
- Remove the border so that it looks cleaner.
- Aligned the text to the left
- Have alterating background for the table rows.
- Use Badge for complexity
- Have Badge for categories in the modal
=> Improve Question Table

frontend/components/Question.tsx, frontend/components/Questions.tsx, frontend/components/QuestionsHeader.tsx, frontend/components/UserHeader.tsx, frontend/components/UserInputField.tsx, frontend/pages/dashboard.tsx, frontend/pages/profile.tsx
The different user will be as shown:
=> Provide different display between user and admin

frontend/components/Question.tsx, frontend/components/Questions.tsx, frontend/components/QuestionsInputField.tsx, frontend/pages/dashboard.tsx
I fix this issue (#81) by bringing the questions and its related variables to the main page (dashboard). Since the InputField will also make changes to the question, the variables is being passed towards QuestionsInputField component too.
The issue is being caused by useEffect of questions. Hence it's fixed by changing the function to be called only when it renders the first time.
However, there might be scoping issues in this fix. Hence, will raise another issue to fix this in later iterations.
=> Fix infinite rendering calling questions bug

backend/authentication_service/.dockerignore, backend/authentication_service/Dockerfile, backend/authentication_service/src/controllers/apitauth.js, backend/authentication_service/src/controllers/authentication.js, backend/user_service/src/controllers/user.js, backend/user_service/src/utility/db.js, development/docker-compose.yml, frontend/components/Question.tsx, frontend/pages/assignment/index.tsx, frontend/pages/dashboard.tsx, frontend/pages/profile.tsx, frontend/pages/signin.tsx, frontend/pages/signup.tsx, gateway/nginx.conf
- Fixed Sign In / Sign Out bug introduced during previous merge resolutions
- Frontend retrieves user role when rendering
- Authentication Service hidden behind API Gateway
- Docker Compose Authentication Related Service
- Default Account added for development environment only
To test app with Authentication:
In `development/` Directory: `docker compose up`
Frontend: `npm run gateway`
- Access at localhost:3000
=> Dockers Authentication Related Services and Bug Fixes

backend/question_scraper/package-lock.json, backend/question_scraper/package.json, backend/question_scraper/serverless.yml, backend/question_scraper/src/scraper.js, backend/question_scraper/src/serverless.js, backend/question_service/README.md, backend/question_service/docker-compose.yml, backend/question_service/package-lock.json, backend/question_service/src/connectdb.js, backend/question_service/src/questionmanager.js, backend/question_service/src/server.js
1. Update Serverless Function to reflect new QuestionService HTTP Verbs
2. Refactor QuestionService to use HTTP verbs. This follows modern REST API good practices
=> Refactor QuestionService to use HTTP verbs

backend/communication_service/server.js, backend/matching_service/server.js, frontend/components/VideoCall.tsx, frontend/components/VideoComponent.tsx, frontend/pages/collaboration.tsx
Video is not started automatically when collaboration begins.
=> Initiate video

backend/question_scraper/README.md, backend/question_scraper/serverless.yml, backend/question_scraper/src/scraper.js, backend/question_scraper/src/serverless.js, backend/question_service/src/questionmanager.js
- Change endpoint to use HTTP POST
- Check for Duplicate Keys early
- Increase Timeout for Serverless Function from 30sec to 60sec
=> Update Serverless Function to fit the new QuestionService

backend/question_service/README.md, backend/question_service/src/questionmanager.js, backend/question_service/src/server.js
- Also, changed the QuestionManager features to async functions
=> Add Random Question feature to QuestionManager

frontend/components/Question.tsx, frontend/pages/profile.tsx
=> Fix Question Display Bug

frontend/components/Question.tsx, frontend/components/Questions.tsx, frontend/components/QuestionsComponent.tsx, frontend/components/QuestionsHeader.tsx, frontend/pages/dashboard.tsx
Questions in the table can now be filtered by complexity.
=> Implement Filtering in question service

frontend/components/LogoutButton.tsx, frontend/components/Question.tsx, frontend/components/Questions.tsx, frontend/components/QuestionsComponent.tsx, frontend/components/QuestionsHeader.tsx, frontend/components/QuestionsInputField.tsx, frontend/components/ToggleMode.tsx, frontend/pages/collaboration.tsx, frontend/pages/dashboard.tsx, frontend/pages/index.tsx, frontend/pages/profile.tsx
Tested on my external monitor and my laptop screen. Both is rendered properly.
However, there is still some misalignment when i do "inspect element". Might be due to the InputField.
Will relook into it.
=> Improve UI on different screens

.gitignore, backend/authentication_service/src/controllers/authentication.js, backend/authentication_service/src/server.js, backend/collaboration_service/.dockerignore, backend/collaboration_service/Dockerfile, backend/communication_service/.dockerignore, backend/communication_service/Dockerfile, backend/history_service/.dockerignore, backend/history_service/Dockerfile, backend/matching_service/.dockerignore, backend/matching_service/Dockerfile, development/docker-compose.yml, development/kube/authentication-service.yaml, development/kube/config.yaml, development/kube/frontend.yaml, development/kube/postgres.yaml, development/kube/question-service.yaml, development/kube/user-service.yaml, frontend/pages/signin.tsx, frontend/pages/signup.tsx, gateway/nginx.conf
Please use this docker-compose file to develop because it will be used to create images for Kubernetes
=> Add remaining services to development/docker-compose.yml

frontend/components/CategoryTag.tsx, frontend/components/MatchButton.tsx, frontend/components/Question.tsx, frontend/pages/collaboration.tsx, frontend/pages/dashboard.tsx
For some questions, when click on the modal, it creates an overflow in the x-axis. This is fixed in this PR.
Also, the menu button for matching has been improved.
Likewise, there was an issue when clicking on the GridItem, allowing Modal to open. This is fixed in this PR too.
=> Fix horizontal overflow bug in modal

backend/collaboration_service/.env, backend/collaboration_service/server.js, backend/communication_service/.env, backend/communication_service/server.js, backend/matching_service/.env, backend/matching_service/model.js, backend/matching_service/modelController.js, backend/matching_service/publisher.js, backend/matching_service/server.js, backend/matching_service/socket.js, frontend/components/CodeEditor.tsx, frontend/components/CreateCustomRoom.tsx, frontend/components/CustomRoomButton.tsx, frontend/components/JoinCustomRoom.tsx, frontend/components/MatchButton.tsx, frontend/components/Sockets/MatchSocketManager.ts, frontend/pages/profile.tsx
Added custom rooms feature and modified environment envs in backend to be stored in env file. Containerisation for collab matching comms and history should be up and working as well.
=> Custom rooms

development/docker-compose.yml, frontend/components/User.tsx, frontend/components/UserHeader.tsx, frontend/pages/dashboard.tsx
Added User Service into dashboard. Currently only getUsers work.
There are still issues such as deleteUsers. At the same time, the box still extrude out of the dashboard.
=> Implement User Service to dashboard

backend/matching_service/modelController.js, backend/matching_service/server.js, frontend/components/CodeEditor.tsx, frontend/components/CreateCustomRoom.tsx, frontend/components/History.tsx, frontend/components/SaveHistoryButton.tsx
Added room leaving through removing in db and error handling when custom room does not exist.
=> cancel match and error handling

development/docker-compose.yml, frontend/pages/collaboration.tsx
=> Implement Elapsed Time and Prev/Next Qns

frontend/components/CategoryCheckbox.tsx, frontend/components/CategoryTag.tsx, frontend/components/CreateCustomRoom.tsx, frontend/components/MatchButton.tsx, frontend/components/Question.tsx, frontend/components/Questions.tsx, frontend/components/QuestionsComponent.tsx, frontend/components/QuestionsInputField.tsx, frontend/pages/collaboration.tsx, frontend/pages/dashboard.tsx, frontend/pages/profile.tsx, frontend/pages/signin.tsx
=> Complexity Menu Item UI

backend/user_service/src/controllers/user.js, frontend/components/CreateCustomRoom.tsx, frontend/components/CustomRoomButton.tsx, frontend/components/JoinCustomRoom.tsx, frontend/components/QuestionsInputField.tsx, frontend/components/User.tsx, frontend/components/UserComponent.tsx, frontend/components/UserHeader.tsx, frontend/components/UserInputField.tsx, frontend/components/Users.tsx, frontend/pages/dashboard.tsx
=> Custom room visuals

backend/collaboration_service/.env, backend/collaboration_service/package-lock.json, backend/collaboration_service/package.json, backend/collaboration_service/server.js, backend/matching_service/server.js, backend/matching_service/socket.js, frontend/components/CodeEditor.tsx, frontend/components/EndMatchButton.tsx, frontend/components/VideoCall.tsx, frontend/pages/collaboration.tsx, frontend/pages/dashboard.tsx, frontend/pages/profile.tsx
Also resolved error from previous merge. Planning to implement notif that triggers when another user leaves the match.
=> Stop watch, auto leave queue

backend/collaboration_service/server.js, backend/communication_service/server.js, backend/history_service/historyController.js, backend/history_service/server.js, backend/matching_service/socket.js, frontend/components/CodeEditor.tsx, frontend/components/EndMatchButton.tsx, frontend/components/History.tsx, frontend/components/Sockets/CollabSocketManager.ts, frontend/components/VideoCall.tsx, frontend/pages/collaboration.tsx, frontend/pages/questionProgress.tsx
I have also removed the option to go through multiple questions in collab for now, too complex to implement within a short period of time.
=> Saved question matched in history and synced match ending logic.

backend/collaboration_service/server.js, backend/matching_service/server.js, frontend/components/CodeEditor.tsx, frontend/components/VideoCall.tsx
fixed the bug where edits are duplicated for the sender. Turns out i accidentally changed socket.to(room) to io.to(room).
=> Code editor duplicating edits

frontend/pages/profile.tsx
Add simple alert dialog feedback for failed matching
=> Add failed matching feedback

frontend/components/History.tsx
I've also added a message for history when there is no history.
=> Fix visuals for history

kubernetes_deployment/communication-service.yaml
- Service reference to deployment was incorrect
=> Correct K8s Communication manifest in Deployment 

backend/collaboration_service/server.js, frontend/components/CodeEditor.tsx, frontend/components/MatchButton.tsx, frontend/components/Sockets/CollabSocketManager.ts, frontend/pages/collaboration.tsx, frontend/pages/dashboard.tsx, frontend/pages/questionProgress.tsx
Progress bar not displaying the right values
code editor collaboration not working
=> More bug fixed

frontend/components/Questions.tsx, frontend/components/QuestionsComponent.tsx, frontend/components/QuestionsInputField.tsx, frontend/pages/dashboard.1.tsx
Fix the bug where only 1 question can be added to question service.
=> Questions addition bug

frontend/components/Question.tsx
I made it such that when a questions clicked to be deleted, there's a confirmation.
=> Provide confirmation for question delete

frontend/components/CreateCustomRoom.tsx, frontend/components/CustomRoomButton.tsx, frontend/components/MatchButton.tsx, frontend/pages/profile.tsx
This is how the UI looks like if the user created the room.
On that note, I've also added a feature such that when the user created a room, the button for entering a queue is disabled.
=> Improve UI for custom room

.github/workflows/aws_deploy.yml, kubernetes_deployment/authentication-service.yaml, kubernetes_deployment/collaboration-service.yaml, kubernetes_deployment/communication-service.yaml, kubernetes_deployment/frontend.yaml, kubernetes_deployment/gateway.yaml, kubernetes_deployment/history-service.yaml, kubernetes_deployment/kustomization.yaml, kubernetes_deployment/matching-service.yaml, kubernetes_deployment/question-service.yaml, kubernetes_deployment/user-service.yaml
- Always pull new image when apply for CD
- Simplifying CD using kubernetes.yaml template
=> Update K8 Config

backend/authentication_service/src/controllers/apitauth.js, backend/authentication_service/src/controllers/authentication.js, frontend/pages/signup.tsx
- User cannot select admin role anymore
- Backend also does not account for the role sent in, hence only User accounts can be create
=> Removing role choice in Signup page as well as in backend

backend/user_service/src/controllers/user.js, frontend/components/History.tsx
In this fix, I've fix the bug where questions appear as HTML element in history.
There is also a bug where there's a page level scrollbar as the model height is too large. I've fixed it in this PR too.
Finally, the paired user seems to be appearing as ids, I've fixed that too.
=> Fix question rendering bug in history
